### ISSUE TITLE
How to enable channels

### ISSUE THREAD

**Issue by eirikh1996** [ryandw11/UltraChat#10]
Hello. I recently installed this on my server. However, I have a great problem: Everytime I use the /channels command, it complains about channels not being enabled. And there is no config option to enable channels

**Comment by ryandw11** [comment]
I'm sorry, I never seem to have responded to this one.
If you still use this plugin then you just have to change the `chat_format: 'normal'` setting in the config to
`chat_format: 'channel'`. After restarting the server it should work.
