### ISSUE TITLE
channels config

### ISSUE THREAD

**Issue by Bene74** [ryandw11/UltraChat#5]
Hello, 

Currently when i try to load in my channels config it keeps wiping it after i format it and start the server. I took your original code from the wiki for the channels page and pasted it in, changing vip to local, adding a JSON and adding a range at the bottom of local (range: 100). this worked the first time i loaded it minus the range feature not working for local chat. i then deleted the space between the semicolin and 100 and put it into the config and now the channels config wipes every time i try to start the server, i have tried with the basic config aswel and it is still doing it. 

Thanks for your time.

**Comment by ryandw11** [comment]
Interesting. So the file is resetting every time you try to change something?

**Comment by Bene74** [comment]
Yes, every time i edit the config, replace the old files and start the server back up it is wiping the channels config.

**Comment by Bene74** [comment]
So i finally figured out what the issue was, its something to do with adding range into it. Everytime it has range it will wipe the file and throws this code in the console. That was an error on my part for not removing that until now. Any suggestion on how to add range into a local channel would be much appreciated. Thanks!
![Capture](https://user-images.githubusercontent.com/55513895/65464272-02923700-de1f-11e9-8df2-66f4aed302b0.PNG)

**Comment by ryandw11** [comment]
oh. You need a space between the colon `:` and the 100.
```yaml
range: 100
```
