### ISSUE TITLE
Chat color breaks

### ISSUE THREAD

**Issue by FranPack** [ryandw11/UltraChat#7]
Chat color breaks when after first line but first line keeps color. I have a picture for reference: https://i.imgur.com/ZNa1yFW.png

**Comment by ryandw11** [comment]
That is more of a minecraft problem. The only solution so far is to put color before every word(which is not that good). I will continue looking for a solution / implement what I said above.

**Comment by wildmaster84** [comment]
what if you create a custom message placeholder to set the color in front of the message

Example: {ChatColor} {message} like (&r{message})
