### ISSUE TITLE
#New player joined, message not displaying anymore

### ISSUE THREAD

**Issue by PRCrafted** [ryandw11/UltraChat#9]
Greetings,

#New player join. If the player hasn't joined the server before then this message will play. If you don't want it put none.
New_Player: '&d%player% has just joined the server for the first time! Welcome!'

^ this seems not to me enabled since it doesn't run in server.  Any tips on how I can enable it?

**Comment by ryandw11** [comment]
Interesting. Seems like a bug. I'll look into it.
